fix(gke): compatible resource naming
redkubes/quickstart pull request #9
Opened 2021-11-15 14:33 UTC by j-zimnowoda

Prevent following errors while ` terraform apply` for gke

```                                                                                           (⎈ otomi-eks-jeho:default)
╷
│ Error: "name" ("498923989146-subnet") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"
│ 
│   with google_compute_subnetwork.subnet,
│   on vpc.tf line 14, in resource "google_compute_subnetwork" "subnet":
│   14:   name          = "${var.project_id}-subnet"
```
```
│ Error: Error creating Network: googleapi: Error 400: Invalid value for field 'resource.name': '498923989146-vpc'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
│ 
│   with google_compute_network.vpc,
│   on vpc.tf line 7, in resource "google_compute_network" "vpc":
│    7: resource "google_compute_network" "vpc" {
```

2021-11-16 09:24 UTC, Morriz approved these changes

2021-11-16 14:21 UTC, 0-sv commented on gcp/gke/variables.tf
> +
```suggestion
```

2021-11-16 14:24 UTC, 0-sv requested changes

2021-11-16 14:24 UTC, 0-sv commented on gcp/gke/variables.tf
> +    error_message = "The cluster_name value must match regex pattern."
```suggestion
    error_message = "The cluster_name variable does not match the required regex pattern (lowercase alphanumerical, can't start or end with hyphen)."
```

2021-11-23 12:41 UTC, j-zimnowoda commented on gcp/gke/variables.tf
> +    error_message = "The cluster_name value must match regex pattern."
done

2021-11-23 12:58 UTC, 0-sv requested changes

2021-11-23 12:58 UTC, 0-sv commented on gcp/gke/variables.tf
> +    error_message = "The cluster_name value must be lowercase and cannot start or end with non-alfanumeric character."
```suggestion
    error_message = "The cluster_name value must be lowercase and cannot start or end with non-alphanumeric character."
```

2021-11-23 13:06 UTC, 0-sv approved these changes

2021-11-23 13:08 UTC, merged